### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by adjieguntoro-dev** [adityalstkp/bundlechecker#8]
<img width="1440" alt="image" src="https://github.com/adityalstkp/bundlechecker/assets/37526430/50ae0896-23ae-437f-bd0d-a607b764be85">

no support: windows 
support: linux amd, mac amd, mac arm (apple silicon)

**Comment by adityalstkp** [comment]
@adjieguntoro-tokped please fix the test bindings, for publish it's expected to be error for now because there's no `NPM_TOKEN`

**Comment by adjieguntoro-dev** [comment]
> @adjieguntoro-tokped please fix the test bindings, for publish it's expected to be error for now because there's no `NPM_TOKEN`

oke om.

**Comment by adjieguntoro-dev** [comment]
dari yang gw baca", runner macos  yang M1 cuma avail di `macos-latest-xlarge` or `macos-13-xlarge`. dan itu ada pricing nya. lanjut?

ref: https://github.com/actions/runner-images/issues/8439

**Comment by kgantchev** [comment]
You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)
